name: Update README Stats

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download generated stats images
        run: |
          curl -L \
            -o overview.svg \
            https://raw.githubusercontent.com/smallghost42/github-stats/generated/overview.svg
          curl -L \
            -o languages.svg \
            https://raw.githubusercontent.com/smallghost42/github-stats/generated/languages.svg

      - name: Update README
        run: |
          git add overview.svg languages.svg README.md
          git commit -m "Update generated stats images" || true
          git push
